---
title: "Planning Dashboard"
output: 
  flexdashboard::flex_dashboard:
    logo: glasses_logo_white_small.png
    favicon: glasses_logo_favicon.jpg
    orientation: rows
    vertical_layout: fill
---

<style>                     
.navbar {
  background-color: #005192;
  border-color: #005192;
}
</style>


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(scales)
library(ggrepel)
library(plotly)
library(DT)
```

Stock KPI
=======================================================================

Row
-----------------------------------------------------------------------

### Grand Total ATP OOS %

```{r}
oos_summary <- read_csv("oos_summary.csv")

oos_summary <- oos_summary %>%
  select(CC, ATP) %>%
  filter(CC == "Grand Total")

x <- oos_summary$ATP * 100

rate <- x
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(0, 9), warning = c(10, 29), danger = c(30, 100)
))
```

### Grand Total ATP + ITR OOS %

```{r}
oos_summary <- read_csv("oos_summary.csv")

oos_summary <- oos_summary %>%
  select(CC, ITR) %>%
  filter(CC == "Grand Total")

y <- oos_summary$ITR * 100

rate <- y
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(0, 9), warning = c(10, 29), danger = c(30, 100)
))
```


### NPI ATP OOS %

```{r}
oos_summary <- read_csv("oos_summary.csv")

oos_summary <- oos_summary %>%
  select(CC, ATP) %>%
  filter(CC == "NPI")

z <- oos_summary$ATP * 100

rate <- z
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(0, 9), warning = c(10, 29), danger = c(30, 100)
))
```

### NPI ATP + ITR OOS %

```{r}
oos_summary <- read_csv("oos_summary.csv")

oos_summary <- oos_summary %>%
  select(CC, ITR) %>%
  filter(CC == "NPI")

z <- oos_summary$ITR * 100

rate <- z
gauge(rate, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(0, 9), warning = c(10, 29), danger = c(30, 100)
))
```


Row
-----------------------------------------------------------------------

### OOS % by Contribution Code

```{r}
oos_summary <- read_csv("oos_summary.csv")

oos_summary <- oos_summary %>%
  select(CC, ATP, ITR, POOS)

oos_summary <- oos_summary %>%
  gather(ATP, ITR, POOS, key = "TYPE", value = "OOS")

#oos_summary$OOS <- oos_summary$OOS * 100

oos_summary$facet = factor(oos_summary$CC,
                           levels = c("A",
                                      "B",
                                      "C",
                                      "D",
                                      "E",
                                      "NPI",
                                      "Grand Total"))

p <- ggplot(data = oos_summary, aes(fill = TYPE, y = OOS, x = CC)) +
  geom_bar(position = "dodge", stat = "identity", width = 0.85) +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 0.25), labels = percent) +
  #scale_y_continuous(labels = percent) +
  theme_minimal() +
  scale_fill_manual("TYPE", values = c("ATP" = "#005192", "ITR" = "#7FA8C8",
                                       "POOS" = "#DFE9F1")) #+
  #geom_text(aes(y = OOS + .9,    # nudge above top of bar
  #              label = paste0(OOS, '')),    # prettify
  #              position = position_dodge(width = .8), 
  #              size = 2.85)

p <- p + theme(axis.title.x = element_blank(),
               axis.title.y = element_blank(),
               legend.position = "bottom"
               )
p <- p + ggtitle(paste0("Updated", " ", Sys.Date()))
p <- p + theme(plot.title = element_text(size = 9))
#p <- p + theme(plot.title = element_text(hjust = -1, vjust = 1))

ggplotly(p) %>%
  layout(legend = list(orientation = "h", y = -.1, x = .0))

```


### Historical ATP OOS % by Contribution Code

```{r}
hist_oos <-
  read_csv("hist_oos.csv")

oos_plot <- hist_oos %>%
  select(`ATP OOS %`, DATE, CC) %>%
  arrange(desc(`ATP OOS %`)) %>%
  filter(CC != "NPI")

oos_plot$`ATP OOS %` <- oos_plot$`ATP OOS %` * 100

oos_plot$DATE <- as.Date(as.POSIXct(oos_plot$DATE))

oos_plot$facet = factor(oos_plot$CC,
                        levels = c("A",
                                   "B",
                                   "C",
                                   "D",
                                   "E",
                                   "NPI",
                                   "Grand Total"))

p <-
  ggplot(data = oos_plot, aes(x = DATE, y = `ATP OOS %`, group = CC)) +
  geom_line(size = 0.45, color = "#3AAADC") +
  #scale_y_continuous(labels = percent) +
  theme(legend.position = "none") +
  theme_bw()

p <- p + facet_wrap(~ facet, nr = 2) +
  theme(strip.background = element_rect(fill = "#005192"),
        strip.text = element_text(#size = 10,
                                  color = "white",
                                  vjust = 0.5,
                                  hjust = 0.5),
        axis.title.x = element_blank(),
        axis.title.y = element_blank())

ggplotly(p)


```

Brand
=======================================================================

Row
-----------------------------------------------------------------------

### Total OOS % by Brand

```{r}
brand_summary <- read_csv("brand_summary.csv")

x <- brand_summary %>%
  select(BRAND, RANK) %>%
  arrange(desc(RANK)) %>%
  distinct() %>%
  select(BRAND)

y <- substr(x$BRAND, start = 1, stop = 10)

brand_summary$BRAND <- factor(brand_summary$BRAND, levels = y)

brand_summary$ATP <- brand_summary$ATP * 100

b <- ggplot(data = brand_summary, aes(fill = "OOS", y = ATP, x = BRAND)) +
  geom_bar(position = "dodge", stat = "identity", width = 0.75) +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 100)) +
  theme_minimal() +
  scale_fill_manual(values = c("#005192")) +
  #geom_text(aes(y = ATP + 5,    # nudge above top of bar
  #              label = paste0(CC, " - ", ATP, '%')),    # prettify
  #              position = position_dodge(width = .9), 
  #              size = 3.5) +
  coord_flip()


b <- b + theme(axis.title.x = element_blank(),
               axis.title.y = element_blank())

ggplotly(b) %>%
    layout(showlegend = FALSE)
```


### NPI OOS % by Brand

```{r}
npi_summary <- read_csv("npi_summary.csv")

x <- npi_summary %>%
  select(BRAND, RANK) %>%
  arrange(desc(RANK)) %>%
  distinct() %>%
  select(BRAND)

y <- substr(x$BRAND, start = 1, stop = 10)

npi_summary$BRAND <- factor(npi_summary$BRAND, levels = y)

npi_summary$ATP <- npi_summary$ATP * 100

b <- ggplot(data = npi_summary, aes(fill = "OOS", y = ATP, x = BRAND)) +
  geom_bar(position = "dodge", stat = "identity", width = 0.75) +
  theme(legend.position = "none") +
  scale_y_continuous(limits = c(0, 100)) +
  theme_minimal() +
  scale_fill_manual(values = c("#005192")) +
  #geom_text(aes(y = ATP + 5,    # nudge above top of bar
  #              label = paste0(CC, " - ", ATP, '%')),    # prettify
  #              position = position_dodge(width = .9), 
  #              size = 3.5) +
  coord_flip()


b <- b + theme(axis.title.x = element_blank(),
               axis.title.y = element_blank())

ggplotly(b) %>%
    layout(showlegend = FALSE)
```


Detail
=======================================================================

Column {data-width=1000}
-----------------------------------------------------------------------

### UPC Level Detail

```{r}
detail <- read_csv("qaf_detail.csv")

detail <- detail %>%
select(
BRAND,
MODELLO,
`GRID VALUE`,
UPC,
CC,
ZZFCAM,
AVAILABLE,
ALLOCATED,
`QUAL-INSP`,
TRANSIT,
L13W_SLS,
L04W_SLS,
LW_SLS,
TW_FCST,
N04W_FCST,
N13W_FCST,
QAF_REV,
`QUANTITA'`,
OOS,
OOS_WITH_TRANSIT,
POOS,
REL,
US03
) %>%
  filter(UPC != 0)

detail$TW_FCST <- round(detail$TW_FCST, digits = 2)
detail$N04W_FCST <- round(detail$N04W_FCST, digits = 2)
detail$N13W_FCST <- round(detail$N13W_FCST, digits = 2)

names(detail)[1] <- c("BRAND")
names(detail)[2] <- c("MODEL")
names(detail)[3] <- c("GRID_VALUE")
names(detail)[4] <- c("EAN_UPC")
names(detail)[5] <- c("CONTR_CODE")
names(detail)[6] <- c("ZZFCAM")
names(detail)[7] <- c("ATP_QTY")
names(detail)[8] <- c("ALLOCATED")
names(detail)[9] <- c("QUAL_INSP")
names(detail)[10] <- c("TRANSIT")
names(detail)[17] <- c("QAF_CALC")
names(detail)[18] <- c("QAF_CURR")
names(detail)[20] <- c("OOS_ITR")

detail <- detail %>%
  arrange(desc(L13W_SLS))

#datatable(detail, rownames = FALSE,
#          extensions = 'Buttons',
#          options = list(dom = 'Bfrtip',
#          buttons = c('excel')))

datatable(
  detail,
  rownames = F,
  extensions = list(
  "ColReorder" = NULL,
  "Buttons" = NULL,
  "FixedColumns" = list(leftColumns = 1)
  ),
  options = list(
  dom = 'BRrlftpi',
  autoWidth = TRUE,
  lengthMenu = list(c(10, 50,-1), c('10', '50', 'All')),
  ColReorder = TRUE,
  scrollX = TRUE,
  fixedColumns = list(leftColumns = 4),
  buttons =
  list(
  extend = 'collection',
  buttons = c('csv', 'excel'),
  text = 'Download'
  ),
  I('colvis')
  ))

```

